// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables for security and deployment flexibility
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://tgqljjfjwelpeansngju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRncWxqamZqd2VscGVhbnNuZ2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2ODU4OTUsImV4cCI6MjA4MTI2MTg5NX0.MbPYVHGgaULaDWup32e1WLFl9OjNAu45O-QV99ab1nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);